### ISSUE TITLE
Debian package: broken link `/usr/bin/sendcrypt`

### ISSUE THREAD

**Issue by jpasquier** [sib-swiss/sendcrypt#17]
Hi,

In the Debian package, `/usr/bin/sendcrypt` in a symlink to `/usr/lib/sendcrypt/sendcrypt`. However, this file does not exist. The correct target should be `/usr/lib/sendcrypt/SendCrypt`. File names are case-sensitive on Linux OS.

Best regards,

Jérôme

**Comment by dterumalai** [comment]
Hi Jérôme, many thanks for reporting the bug in the Linux version. I have to apologize as we didn't manage to properly test this version contrary to the windows and macos version. I am very interested to test it further with you if you have the time, could you please contact us here: spsp-support@sib.swiss so that we can get a bit more context? Thanks again and have a nice day!

**Comment by jpasquier** [comment]
Last commit solves the issue. Thank you
